import bcrypt from "bcryptjs";
import { CategoryRecord, ProductRecord, SpecificationItem, AdminUserRecord, CustomerStoryRecord } from "./types";

export const initialCategories: CategoryRecord[] = [
  {
    id: "cat_passenger",
    name: "Passenger Vehicle",
    nameHi: "पैसेंजर ई-रिक्शा",
    slug: "passenger-vehicle",
    description: "Battery powered electric three-wheelers designed for urban and suburban passenger commute.",
    displayOrder: 1,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_cargo",
    name: "Cargo / Loader",
    nameHi: "लोडर / मालवाहक",
    slug: "cargo-loader",
    description: "Heavy-duty electric cargo loaders and delivery vans with reinforced flatbeds and containers.",
    displayOrder: 2,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_erickshaw",
    name: "E-Rickshaw",
    nameHi: "ई-रिक्शा",
    slug: "e-rickshaw",
    description: "Standard passenger electric three wheelers with CMVR compliance.",
    displayOrder: 3,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_ecart",
    name: "E-Cart",
    nameHi: "ई-कार्ट",
    slug: "e-cart",
    description: "Utility electric carts for campus, warehouse and short-distance municipal handling.",
    displayOrder: 4,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_eloader",
    name: "Electric Loader",
    nameHi: "इलेक्ट्रिक लोडर",
    slug: "electric-loader",
    description: "High payload electric three wheelers for transport of industrial and agricultural loads.",
    displayOrder: 5,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_other",
    name: "Other",
    nameHi: "अन्य",
    slug: "other",
    description: "Specialized electric mobility solutions and custom commercial builds.",
    displayOrder: 6,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const defaultSpecificationTemplates = [
  { label: "Motor Type", labelHi: "मोटर प्रकार", defaultValue: "High Torque BLDC Electric Motor", defaultValueHi: "हाई टॉर्क बीएलडीसी इलेक्ट्रिक मोटर", icon: "zap", displayOrder: 1 },
  { label: "Battery Chemistry", labelHi: "बैटरी प्रकार", defaultValue: "Lead-Acid / Advanced Lithium-Ion Option", defaultValueHi: "लेड-एसिड / आधुनिक लिथियम-आयन विकल्प", icon: "battery", displayOrder: 2 },
  { label: "Battery Capacity", labelHi: "बैटरी क्षमता", defaultValue: "Configurable upon enquiry", defaultValueHi: "पूछताछ अनुसार विन्यास योग्य", icon: "battery", displayOrder: 3 },
  { label: "Estimated Range", labelHi: "अनुमानित रेंज", defaultValue: "80 - 110 km per single charge (estimated)", defaultValueHi: "80 - 110 किमी प्रति सिंगल चार्ज (अनुमानित)", icon: "gauge", displayOrder: 4 },
  { label: "Charging Time", labelHi: "चार्जिंग समय", defaultValue: "4 - 8 Hours depending on battery system", defaultValueHi: "बैटरी सिस्टम के अनुसार 4 - 8 घंटे", icon: "clock", displayOrder: 5 },
  { label: "Capacity (Seats / Payload)", labelHi: "क्षमता (सीट / वजन)", defaultValue: "Driver + 4 Passengers (Govt. Approved Spec)", defaultValueHi: "चालक + 4 यात्री (सरकारी प्रमाणित)", icon: "users", displayOrder: 6 },
  { label: "Top Speed", labelHi: "अधिकतम गति", defaultValue: "25 km/h (CMVR Compliant)", defaultValueHi: "25 किमी/घंटा (सीएमवीआर अनुरूप)", icon: "gauge", displayOrder: 7 },
  { label: "Braking System", labelHi: "ब्रेकिंग सिस्टम", defaultValue: "Drum Brakes with Mechanical Parking Brake", defaultValueHi: "ड्रम ब्रेक व मैकेनिकल हैंडब्रेक", icon: "layers", displayOrder: 8 },
  { label: "Chassis Frame", labelHi: "चेसिस फ्रेम", defaultValue: "Heavy Duty Tubular Steel Frame", defaultValueHi: "हैवी ड्यूटी ट्यूबलर स्टील फ्रेम", icon: "layers", displayOrder: 9 },
  { label: "Warranty", labelHi: "वारंटी", defaultValue: "Manufacturer Warranty on Motor & Drivetrain", defaultValueHi: "मोटर व ड्राइवट्रेन पर निर्माता वारंटी", icon: "shield", displayOrder: 10 },
];

export const initialProducts: ProductRecord[] = [
  {
    id: "prod_sargam_victor",
    slug: "sargam-victor-passenger",
    name: "Sargam Victor Passenger E-Rickshaw",
    nameHi: "सरगम विक्टर पैसेंजर ई-रिक्शा",
    categoryId: "cat_passenger",
    categoryName: "Passenger Vehicle",
    shortDescription: "Rugged tubular chassis, ergonomic driver cabin, and cushioned passenger bench seating optimized for city and suburban transit.",
    shortDescriptionHi: "मजबूत ट्यूबलर चेसिस, आरामदायक ड्राइवर केबिन और शहर के सवारी रूटों के लिए गद्देदार पैसेंजर सीटें।",
    fullDescription: "Engineered specifically for heavy daily commercial mileage, the Sargam Victor passenger electric rickshaw provides drivers with low operational cost and passengers with a smooth, stable ride. Built with a reinforced steel chassis, reliable suspension, and high-efficiency electric drivetrain.",
    fullDescriptionHi: "भारी दैनिक व्यावसायिक आवागमन के लिए विशेष रूप से निर्मित, सरगम विक्टर ई-रिक्शा चालकों को अत्यंत कम संचालन खर्च और सवारियों को आरामदायक व स्थिर सफर देता है।",
    mainImage: "/images/SARGAM-VICTOR-BLUE-2.webp",
    galleryImages: [
      "/images/SARGAM-VICTOR-BLUE-2.webp",
      "/images/Sargam-E-Ride.webp",
      "/images/rickshaw-blue.webp",
      "/images/rickshaw-red.webp"
    ],
    priceMode: "on_enquiry",
    price: null,
    currency: "INR",
    featured: true,
    status: "published",
    displayOrder: 1,
    model3dUrl: "/models/balaji-rickshaw.glb",
    specifications: [
      { id: "spec_1_1", productId: "prod_sargam_victor", label: "Motor Type", labelHi: "मोटर प्रकार", value: "High Torque BLDC Electric Motor", valueHi: "हाई टॉर्क बीएलडीसी इलेक्ट्रिक मोटर", icon: "zap", displayOrder: 1 },
      { id: "spec_1_2", productId: "prod_sargam_victor", label: "Battery Chemistry", labelHi: "बैटरी प्रकार", value: "Lead-Acid / Advanced Lithium-Ion Option", valueHi: "लेड-एसिड / आधुनिक लिथियम-आयन विकल्प", icon: "battery", displayOrder: 2 },
      { id: "spec_1_3", productId: "prod_sargam_victor", label: "Battery Capacity", labelHi: "बैटरी क्षमता", value: "Configurable upon enquiry", valueHi: "पूछताछ अनुसार विन्यास योग्य", icon: "battery", displayOrder: 3 },
      { id: "spec_1_4", productId: "prod_sargam_victor", label: "Estimated Range", labelHi: "अनुमानित रेंज", value: "80 - 110 km per single charge (estimated)", valueHi: "80 - 110 किमी प्रति सिंगल चार्ज (अनुमानित)", icon: "gauge", displayOrder: 4 },
      { id: "spec_1_5", productId: "prod_sargam_victor", label: "Charging Time", labelHi: "चार्जिंग समय", value: "4 - 8 Hours depending on battery system", valueHi: "बैटरी सिस्टम के अनुसार 4 - 8 घंटे", icon: "clock", displayOrder: 5 },
      { id: "spec_1_6", productId: "prod_sargam_victor", label: "Capacity (Seats / Payload)", labelHi: "क्षमता (सीट / वजन)", value: "Driver + 4 Passengers (Govt. Approved Spec)", valueHi: "चालक + 4 यात्री (सरकारी प्रमाणित)", icon: "users", displayOrder: 6 },
      { id: "spec_1_7", productId: "prod_sargam_victor", label: "Top Speed", labelHi: "अधिकतम गति", value: "25 km/h (CMVR Compliant)", valueHi: "25 किमी/घंटा (सीएमवीआर अनुरूप)", icon: "gauge", displayOrder: 7 },
      { id: "spec_1_8", productId: "prod_sargam_victor", label: "Braking System", labelHi: "ब्रेकिंग सिस्टम", value: "Drum Brakes with Mechanical Parking Brake", valueHi: "ड्रम ब्रेक व मैकेनिकल हैंडब्रेक", icon: "layers", displayOrder: 8 },
      { id: "spec_1_9", productId: "prod_sargam_victor", label: "Chassis Frame", labelHi: "चेसिस फ्रेम", value: "Heavy Duty Tubular Steel Frame", valueHi: "हैवी ड्यूटी ट्यूबलर स्टील फ्रेम", icon: "layers", displayOrder: 9 },
      { id: "spec_1_10", productId: "prod_sargam_victor", label: "Warranty", labelHi: "वारंटी", value: "Manufacturer Warranty on Motor & Drivetrain", valueHi: "मोटर व ड्राइवट्रेन पर निर्माता वारंटी", icon: "shield", displayOrder: 10 },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod_king_cargo_express",
    slug: "king-cargo-express-loader",
    name: "King Cargo Express E-Loader",
    nameHi: "किंग कार्गो एक्सप्रेस ई-लोडर",
    categoryId: "cat_cargo",
    categoryName: "Cargo / Loader",
    shortDescription: "Heavy payload open cargo deck with fold-down drop gates, reinforced rear leaf springs, and high-torque hill assist gearing.",
    shortDescriptionHi: "मजबूत ओपन कार्गो डाला, झुकने वाले साइड गेट, हैवी लीफ स्प्रिंग सस्पेंशन और भारी माल ढुलाई गियरिंग।",
    fullDescription: "Purpose-built for distributors, mandi transporters, construction supply yards, and express cargo routes in Punjab. The King Cargo Express loader offers a rugged steel load bed capable of handling substantial daily commercial tonnage with zero tailpipe emissions.",
    fullDescriptionHi: "पंजाब के व्यापारियों, मंडी आढ़तियों और हार्डवेयर सप्लायरों के लिए विशेष रूप से तैयार किया गया मजबूत किंग कार्गो इलेक्ट्रिक लोडर।",
    mainImage: "/images/rickshaw-green.webp",
    galleryImages: [
      "/images/rickshaw-green.webp",
      "/images/rickshaw-blue.webp",
      "/images/rickshaw-red.webp"
    ],
    priceMode: "on_enquiry",
    price: null,
    currency: "INR",
    featured: true,
    status: "published",
    displayOrder: 2,
    model3dUrl: null,
    specifications: [
      { id: "spec_2_1", productId: "prod_king_cargo_express", label: "Motor Type", labelHi: "मोटर प्रकार", value: "High Torque Commercial BLDC Motor", valueHi: "हैवी ड्यूटी बीएलडीसी मोटर", icon: "zap", displayOrder: 1 },
      { id: "spec_2_2", productId: "prod_king_cargo_express", label: "Battery Chemistry", labelHi: "बैटरी प्रकार", value: "Heavy-Duty Deep Cycle / Lithium-Ion Option", valueHi: "हैवी ड्यूटी डीप साइकिल / लिथियम आयन विकल्प", icon: "battery", displayOrder: 2 },
      { id: "spec_2_3", productId: "prod_king_cargo_express", label: "Battery Capacity", labelHi: "बैटरी क्षमता", value: "Custom Heavy Commercial Capacity", valueHi: "व्यावसायिक उपयोग अनुसार क्षमता", icon: "battery", displayOrder: 3 },
      { id: "spec_2_4", productId: "prod_king_cargo_express", label: "Estimated Range", labelHi: "अनुमानित रेंज", value: "70 - 100 km per charge (payload dependent)", valueHi: "70 - 100 किमी प्रति चार्ज (वजन अनुसार)", icon: "gauge", displayOrder: 4 },
      { id: "spec_2_5", productId: "prod_king_cargo_express", label: "Charging Time", labelHi: "चार्जिंग समय", value: "5 - 8 Hours", valueHi: "5 - 8 घंटे", icon: "clock", displayOrder: 5 },
      { id: "spec_2_6", productId: "prod_king_cargo_express", label: "Capacity (Seats / Payload)", labelHi: "क्षमता (सीट / वजन)", value: "Rated Payload up to 500 kg (Commercial Spec)", valueHi: "500 किलोग्राम तक रेटेड पेलोड क्षमता", icon: "package", displayOrder: 6 },
      { id: "spec_2_7", productId: "prod_king_cargo_express", label: "Top Speed", labelHi: "अधिकतम गति", value: "25 km/h", valueHi: "25 किमी/घंटा", icon: "gauge", displayOrder: 7 },
      { id: "spec_2_8", productId: "prod_king_cargo_express", label: "Braking System", labelHi: "ब्रेकिंग सिस्टम", value: "Reinforced Hydraulic / Mechanical Drum", valueHi: "मजबूत ड्रम ब्रेक सिस्टम", icon: "layers", displayOrder: 8 },
      { id: "spec_2_9", productId: "prod_king_cargo_express", label: "Chassis Frame", labelHi: "चेसिस फ्रेम", value: "Reinforced Ladder Frame with Drop Gates", valueHi: "ड्रॉप गेट्स युक्त मजबूत लैडर फ्रेम", icon: "layers", displayOrder: 9 },
      { id: "spec_2_10", productId: "prod_king_cargo_express", label: "Warranty", labelHi: "वारंटी", value: "Manufacturer Warranty on Motor & Drivetrain", valueHi: "मोटर व ड्राइवट्रेन पर निर्माता वारंटी", icon: "shield", displayOrder: 10 },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod_balaji_city_passenger",
    slug: "balaji-city-passenger-standard",
    name: "Balaji City Passenger E-Rickshaw",
    nameHi: "बालाजी सिटी पैसेंजर ई-रिक्शा",
    categoryId: "cat_passenger",
    categoryName: "Passenger Vehicle",
    shortDescription: "Agile, dependable city commuter model featuring wide footboards, protective rain curtains, and balanced shock-absorbing front suspension.",
    shortDescriptionHi: "शहर के संकरे रास्तों के लिए फुर्तीला ई-रिक्शा, चौड़े पायदान, बरसाती परदे और मजबूत फ्रंट सस्पेंशन।",
    fullDescription: "A trusted companion for owner-drivers navigating busy bazaar streets, colony links, and railway station routes across Jalandhar and surrounding districts.",
    fullDescriptionHi: "जालंधर और आसपास के व्यस्त बाजारों, कॉलोनियों और रेलवे स्टेशन रूटों के लिए बेहद भरोसेमंद साथी ई-रिक्शा।",
    mainImage: "/products/balaji-city-passenger-standard.png",
    galleryImages: [
      "/products/balaji-city-passenger-standard.png",
      "/products/balaji-passenger.png"
    ],
    priceMode: "on_enquiry",
    price: null,
    currency: "INR",
    featured: true,
    status: "published",
    displayOrder: 3,
    model3dUrl: null,
    specifications: [
      { id: "spec_3_1", productId: "prod_balaji_city_passenger", label: "Motor Type", labelHi: "मोटर प्रकार", value: "Standard Efficiency 1000W BLDC Motor", valueHi: "1000 वाट कुशल बीएलडीसी मोटर", icon: "zap", displayOrder: 1 },
      { id: "spec_3_2", productId: "prod_balaji_city_passenger", label: "Battery Chemistry", labelHi: "बैटरी प्रकार", value: "Tubular Lead-Acid or Lithium Option", valueHi: "ट्यूबलर लेड-एसिड या लिथियम विकल्प", icon: "battery", displayOrder: 2 },
      { id: "spec_3_3", productId: "prod_balaji_city_passenger", label: "Battery Capacity", labelHi: "बैटरी क्षमता", value: "48V Commercial Configuration", valueHi: "48V कमर्शियल विन्यास", icon: "battery", displayOrder: 3 },
      { id: "spec_3_4", productId: "prod_balaji_city_passenger", label: "Estimated Range", labelHi: "अनुमानित रेंज", value: "75 - 95 km per charge", valueHi: "75 - 95 किमी प्रति चार्ज", icon: "gauge", displayOrder: 4 },
      { id: "spec_3_5", productId: "prod_balaji_city_passenger", label: "Charging Time", labelHi: "चार्जिंग समय", value: "6 - 8 Hours", valueHi: "6 - 8 घंटे", icon: "clock", displayOrder: 5 },
      { id: "spec_3_6", productId: "prod_balaji_city_passenger", label: "Capacity (Seats / Payload)", labelHi: "क्षमता (सीट / वजन)", value: "Driver + 4 Passenger (Standard Approved)", valueHi: "चालक + 4 यात्री मानक", icon: "users", displayOrder: 6 },
      { id: "spec_3_7", productId: "prod_balaji_city_passenger", label: "Top Speed", labelHi: "अधिकतम गति", value: "25 km/h", valueHi: "25 किमी/घंटा", icon: "gauge", displayOrder: 7 },
      { id: "spec_3_8", productId: "prod_balaji_city_passenger", label: "Braking System", labelHi: "ब्रेकिंग सिस्टम", value: "Front & Rear Drum Brakes", valueHi: "अगले व पिछले ड्रम ब्रेक", icon: "layers", displayOrder: 8 },
      { id: "spec_3_9", productId: "prod_balaji_city_passenger", label: "Chassis Frame", labelHi: "चेसिस फ्रेम", value: "Tubular Steel Frame with Passenger Grab Rails", valueHi: "यात्री सुरक्षा रेलिंग युक्त ट्यूबलर फ्रेम", icon: "layers", displayOrder: 9 },
      { id: "spec_3_10", productId: "prod_balaji_city_passenger", label: "Warranty", labelHi: "वारंटी", value: "Manufacturer Warranty on Motor & Drivetrain", valueHi: "मोटर व ड्राइवट्रेन पर निर्माता वारंटी", icon: "shield", displayOrder: 10 },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "prod_balaji_delivery_van",
    slug: "balaji-delivery-closed-van",
    name: "Balaji Delivery Van E-Carrier",
    nameHi: "बालाजी डिलीवरी वैन ई-कैरियर",
    categoryId: "cat_cargo",
    categoryName: "Cargo / Loader",
    shortDescription: "Fully enclosed weatherproof metal cargo box with lockable rear double doors for secure courier, grocery, and pharmaceutical deliveries.",
    shortDescriptionHi: "सुरक्षित ताला-बंद वाटरप्रूफ कंटेनर बॉडी, कूरियर, ग्रोसरी व पार्सल डिलीवरी के लिए आदर्श।",
    fullDescription: "An indispensable asset for last-mile logistics companies, departmental store deliveries, catering services, and secure urban parcel transit.",
    fullDescriptionHi: "ई-कॉमर्स, कूरियर और पार्सल कंपनियों के लिए हर मौसम में माल को सुरक्षित व सूखा रखने वाली इलेक्ट्रिक डिलीवरी वैन।",
    mainImage: "/products/balaji-delivery-closed-van.png",
    galleryImages: [
      "/products/balaji-delivery-closed-van.png",
      "/products/balaji-van.png"
    ],
    priceMode: "on_enquiry",
    price: null,
    currency: "INR",
    featured: false,
    status: "published",
    displayOrder: 4,
    model3dUrl: null,
    specifications: [
      { id: "spec_4_1", productId: "prod_balaji_delivery_van", label: "Motor Type", labelHi: "मोटर प्रकार", value: "High Efficiency 1200W BLDC Motor", valueHi: "1200 वाट उच्च क्षमता बीएलडीसी मोटर", icon: "zap", displayOrder: 1 },
      { id: "spec_4_2", productId: "prod_balaji_delivery_van", label: "Battery Chemistry", labelHi: "बैटरी प्रकार", value: "Heavy-Duty Deep Cycle Lead-Acid / Lithium", valueHi: "डीप साइकिल लेड-एसिड या लिथियम", icon: "battery", displayOrder: 2 },
      { id: "spec_4_3", productId: "prod_balaji_delivery_van", label: "Battery Capacity", labelHi: "बैटरी क्षमता", value: "Optimized for Multi-Stop Rounds", valueHi: "मल्टी-स्टॉप डिलीवरी अनुकूलित क्षमता", icon: "battery", displayOrder: 3 },
      { id: "spec_4_4", productId: "prod_balaji_delivery_van", label: "Estimated Range", labelHi: "अनुमानित रेंज", value: "70 - 90 km per charge", valueHi: "70 - 90 किमी प्रति चार्ज", icon: "gauge", displayOrder: 4 },
      { id: "spec_4_5", productId: "prod_balaji_delivery_van", label: "Charging Time", labelHi: "चार्जिंग समय", value: "5 - 7 Hours", valueHi: "5 - 7 घंटे", icon: "clock", displayOrder: 5 },
      { id: "spec_4_6", productId: "prod_balaji_delivery_van", label: "Capacity (Seats / Payload)", labelHi: "क्षमता (सीट / वजन)", value: "Enclosed Volume with 400 kg Payload", valueHi: "बंद कंटेनर व 400 किलोग्राम भार क्षमता", icon: "package", displayOrder: 6 },
      { id: "spec_4_7", productId: "prod_balaji_delivery_van", label: "Top Speed", labelHi: "अधिकतम गति", value: "25 km/h", valueHi: "25 किमी/घंटा", icon: "gauge", displayOrder: 7 },
      { id: "spec_4_8", productId: "prod_balaji_delivery_van", label: "Braking System", labelHi: "ब्रेकिंग सिस्टम", value: "Front & Rear Mechanical Drum", valueHi: "अगले व पिछले ड्रम ब्रेक", icon: "layers", displayOrder: 8 },
      { id: "spec_4_9", productId: "prod_balaji_delivery_van", label: "Chassis Frame", labelHi: "चेसिस फ्रेम", value: "Reinforced Enclosed Cargo Body with Rear Twin Doors", valueHi: "दोहरे पिछले दरवाजों युक्त वाटरप्रूफ बॉडी", icon: "layers", displayOrder: 9 },
      { id: "spec_4_10", productId: "prod_balaji_delivery_van", label: "Warranty", labelHi: "वारंटी", value: "Manufacturer Warranty on Motor & Drivetrain", valueHi: "मोटर व ड्राइवट्रेन पर निर्माता वारंटी", icon: "shield", displayOrder: 10 },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export async function createDefaultAdmin(): Promise<AdminUserRecord> {
  const email = process.env.ADMIN_EMAIL || "balajimotors.etawah@gmail.com";
  const rawPassword = process.env.ADMIN_PASSWORD || "BalajiAdmin@2026!";
  const passwordHash = process.env.ADMIN_PASSWORD_HASH || (await bcrypt.hash(rawPassword, 12));

  return {
    id: "admin_master_1",
    email,
    passwordHash,
    name: "Balaji Motors Admin",
    role: "admin",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

export const initialCustomers: CustomerStoryRecord[] = [
  {
    id: "cust_1",
    name: "Gurpreet Singh",
    nameHi: "गुरप्रीत सिंह",
    location: "Rama Mandi, Jalandhar",
    locationHi: "रामा मंडी, जालंधर",
    vehicleName: "Sargam Victor Passenger E-Rickshaw",
    vehicleNameHi: "सरगम विक्टर पैसेंजर ई-रिक्शा",
    deliveryDate: "August 2026",
    deliveryDateHi: "अगस्त 2026",
    rating: 5,
    quote: "Balaji Motors made my loan approval so smooth and delivered the Sargam Victor within 2 days! My daily earning increased and the battery gives 100+ km easily on full charge.",
    quoteHi: "बालाजी मोटर्स से लोन बहुत आसानी से पास हो गया और मात्र 2 दिन में गाड़ी मिल गई। अब रोज 100+ किमी आराम से चलता है और कमाई भी बढ़ गई है।",
    image: "/images/SARGAM-VICTOR-BLUE-2.webp",
    featured: true,
    displayOrder: 1,
    createdAt: "2026-08-15T10:00:00.000Z",
    updatedAt: "2026-08-15T10:00:00.000Z",
  },
  {
    id: "cust_2",
    name: "Surjit Kumar",
    nameHi: "सुरजीत कुमार",
    location: "GT Road, Phagwara",
    locationHi: "जीटी रोड, फगवाड़ा",
    vehicleName: "King Cargo Express E-Loader",
    vehicleNameHi: "किंग कार्गो एक्सप्रेस ई-लोडर",
    deliveryDate: "July 2026",
    deliveryDateHi: "जुलाई 2026",
    rating: 5,
    quote: "We carry wholesale fruit crates from Jalandhar mandi every morning. The King Cargo heavy leaf spring suspension handles 450 kg without any strain. Huge fuel savings!",
    quoteHi: "हम रोज सुबह जालंधर मंडी से फलों के क्रेट्स लाते हैं। किंग कार्गो 450 किलो वजन भी बिना किसी परेशानी के खींचता है। डीजल का भारी खर्च बच रहा है।",
    image: "/images/rickshaw-green.webp",
    featured: true,
    displayOrder: 2,
    createdAt: "2026-07-20T10:00:00.000Z",
    updatedAt: "2026-07-20T10:00:00.000Z",
  },
  {
    id: "cust_3",
    name: "Manjit Singh",
    nameHi: "मनजीत सिंह",
    location: "Sultanpur Lodhi, Kapurthala",
    locationHi: "सुल्तानपुर लोधी, कपूरथला",
    vehicleName: "MKB Deluxe Passenger E-Rickshaw",
    vehicleNameHi: "एमकेबी डीलक्स पैसेंजर ई-रिक्शा",
    deliveryDate: "June 2026",
    deliveryDateHi: "जून 2026",
    rating: 5,
    quote: "The alloy wheels and comfortable rexine seating make my passengers choose my rickshaw first. Balaji Motors team gave full support with RTO passing and documentation.",
    quoteHi: "अलॉय व्हील और आरामदायक सीटों की वजह से सवारियां मेरी गाड़ी में बैठना पसंद करती हैं। आरटीओ पासिंग में भी बालाजी मोटर्स ने पूरा सहयोग दिया।",
    image: "/images/rickshaw-white.webp",
    featured: true,
    displayOrder: 3,
    createdAt: "2026-06-12T10:00:00.000Z",
    updatedAt: "2026-06-12T10:00:00.000Z",
  },
  {
    id: "cust_4",
    name: "Rajinder Pal",
    nameHi: "राजिंदर पाल",
    location: "Nakodar Road, Jalandhar",
    locationHi: "नकोदर रोड, जालंधर",
    vehicleName: "Balaji City Passenger E-Rickshaw",
    vehicleNameHi: "बालाजी सिटी पैसेंजर ई-रिक्शा",
    deliveryDate: "May 2026",
    deliveryDateHi: "मई 2026",
    rating: 5,
    quote: "Excellent after-sales service. Whenever I need a routine checkup or greasing, Balaji Motors workshop attends to it immediately with genuine parts.",
    quoteHi: "बिक्री के बाद की सर्विस बहुत शानदार है। जब भी सर्विस या ग्रीसिंग की जरूरत होती है, वर्कशॉप में तुरंत काम हो जाता है।",
    image: "/images/rickshaw-red.webp",
    featured: true,
    displayOrder: 4,
    createdAt: "2026-05-05T10:00:00.000Z",
    updatedAt: "2026-05-05T10:00:00.000Z",
  },
];